name: cosinuss_lib
description: A library for using Cosinuss sensors in Dart
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.0.1
  build_runner: ^2.1.7
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.3.1
  json_annotation: ^4.7.0
  web_socket_channel: ^2.2.0
