name: cosinuss_lib
description: A library for using Cosinuss sensors in Dart
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter_blue_plus: ^1.3.1
